// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Proyecto.Models;
using System;

namespace Proyecto.Migrations
{
    [DbContext(typeof(RegistrarContext))]
    [Migration("20180223180518_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Proyecto.Models.Registrar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Apellidos");

                    b.Property<string>("NickName");

                    b.Property<string>("Nombre");

                    b.Property<string>("Password");

                    b.HasKey("ID");

                    b.ToTable("Registrar");
                });
#pragma warning restore 612, 618
        }
    }
}
